### ISSUE TITLE
There is no engineering team in the flashbots github organization

### ISSUE THREAD

**Issue by come-maiz** [flashbots/flashbots-repository-template#2]
The engineering members of flashbots should have write permissions to all the software repositories.

To do this, we can create an engineering team in the github organization.

**Comment by fiiiu** [comment]
Done, https://github.com/orgs/flashbots/teams/engineering.

Added myself automatically when creating the team, feel free to remove me.

Tagging @Souptacular for updating the onboarding + offboarding guides.
